### ISSUE TITLE
垃圾数据删除问题

### ISSUE THREAD

**Issue by meilihao** [tango-contrib/session-ssdb#1]
假设使用CookieTracker,当cookie失效或被删除时,该sessionId在hset里的数据就没法删除了.

**Comment by lunny** [comment]
有超时时间的。超时会自动删除。

**Comment by meilihao** [comment]
ssdb文档上标明,expire设置 key,只针对 KV 类型.Hashmap没有超时时间吧.

**Comment by lunny** [comment]
看到了。。。想当然以为跟redis一样了。

**Comment by lunny** [comment]
@ideawu，ssdb能够解决这个问题吗？

**Comment by ideawu** [comment]
超时只能适用于kv, 这个限制没有改变的计划. 如果有需求, 要么换成kv, 要么自己实现.

**Comment by lunny** [comment]
暂时可以使用 [github.com/tango-contrib/session-ledis](https://github.com/tango-contrib/session-ledis)  替代
